### ISSUE TITLE
(continuation of .NET Framework issue !)

### ISSUE THREAD

**Issue by Deus-nsf** [m4rcelpl/UpdateMyApp-Net-Standard#1]
I've been trying the app today, first, the inclusion of the library works out of the box and that's really great.
For SetUrlToXml() and SetCurrentVersion() it returns true if my parameters are correct which is great too,
but when I call CheckForNewVersionAsync() it never finishes the task, and the output window shows things like :

"DllImport error loading library './libmono-btls-shared'" (I don't paste everything the log is very huge)

Maybe I'm missing some libraries in my project ? I'm using xamarin.android which is supposed to have mono libraries.

**Comment by Deus-nsf** [comment]
mm... looks like even when I do it manually : 

                    HttpClient client = new HttpClient();
                    await client.GetAsync( pathForUpdate );

it still gives me the same error, might not come form your code then, damn..
it matches : 

                    var getXml = await client.GetAsync(UrlToXML);

from your code, something is going on with this.. maybe an authentication problem ?

**Comment by m4rcelpl** [comment]
Yes, this is xamarin specific error. I don't have any experience with xamarin but try this:
https://docs.microsoft.com/pl-pl/xamarin/cross-platform/macios/http-stack
or this:
https://forums.xamarin.com/discussion/7719/using-httpclient

My librery is Open source, you can make fork or download UpdateMyApp.cs and add to your project. Then add your own reference to HttpClient which will work with xamarin.

**Comment by Deus-nsf** [comment]
Dont worry, I figured it out, HttpClient won't work correctly with mono libraries so I started an other code from scratch using WebClient instead (which is supposed to be deprecated ?) and it works !
So by using WebClient I was able to download any file I wanted and store it in the phone (as long as I have permission to write on the chosen location)
Trying to figure how I could download files with Xamarin I writed something completely new that is very specific to my project so I can't make any pull request sadly, but the idea would be to have some kind of flag to detect if it's a xamarin app and if it is, function with a WebClient instead of a HttpClient and download your file with webClientInstance.Download("file_location", "destination");
Your approach helped me a lot however ! Thank you :)
